before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: P61gxkUGSXPbth+eUoSjRha+oiximLZ+563WxpO7CRhFCmBf1IzPjYe4FhqJyeeEQu+FaOJMVb2dsUou6bUz4ZvdiHtcUcBrWOLHt0oe5YoX6tQ/TcVYLj6KsED/yqKGGJUyYChxhiJTc24Z/fd5EkYu4lv8g7xDMZjP1Sc7H8PjvKiLgRzYhlRMMEwlemkKi9CCcwczGK/rIC1evaCxWjPqI59vwlHJ5e06qXpQcOiEFoepY8DyIhRUxBHuV7BpGY/OAY1NOveMr3q1YNW68WhuPlwMDimQ2evmFWfmORtzFXmoErY37MAowLpgOUWpljWoACLlnCGEUO9OwlL0J3ARKPiehGrSO8dwiH8yR7tNt/C/8YxUIZLnOC6dbQz/xhuQwOu/dgcDX7082xvszbH1zlxp7Y/++OWUU4EftayBNIznQd5M/KQJAelf3TXcNuYZXGOzkSmh3uOnQjjstyCjM+CUd92TGwhePfJrCOCB7rBLwkFyRrL0wuiSDdzbHSfMfu9jYFLS5HS+WQMOIWta0XPZpsWWvzkHh9WbQAWAQgzWyzvaSMegjL2rCABeimMQUhmbXw1aeDJ7q69FAkovpPYzYwGFWD3Pl2N93bBfRFHdLHbyrFVzgZtgbsKuirGqdrbtY5E6gPaZKu7RPAnRHFD9BSKN2YbBDhth/oA= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
